services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    image: sc_frontend_dev
    container_name: sc_frontend_dev
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "4200:4200"
    command: npx ng serve --host 0.0.0.0 --poll 500
    networks:
      - sc_network